
default_platform(:android)

platform :android do
  desc "firebase app distribution for android"
  lane :firebase_distribution do
   sh "flutter clean"
   sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons" 
  firebase_app_distribution(
    app: "1:262753937520:android:8e97b744d413d3e81aecb5",
    firebase_cli_token: "1//09x8PmjsD38JTCgYIARAAGAkSNwF-L9IrGzTzNBXeuepM8tjovXcXrLBsQtIEazKBd-wBe-Z1M8VHIK16aRcgKJ6tuPKeB2RTeTY",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "mmoud2031@gmail.com",
    release_notes: "This is a new release note from fastlane"
)
  end
end

